// template generated by typing rnf using installed extension
import { View, Text,Image, StyleSheet } from 'react-native'
import React from 'react'
import { Colors } from '@/constants/Colors'

export default function Login() {
  return (
    <View>
    <View>
      <Image source={require("./../assets/images/login.png")}
      style={{width:'100%',
        height:400
      }}
      />
    </View>
    <View style={styles.container}>
<Text style={{fontSize:28,fontFamily:'outfit-bold',textAlign:'center',marginTop:20}}>
Ai Travel Planner
</Text>
<Text style={{
  fontFamily:'outfit',
  fontSize:17,
  textAlign:'center',
  color:Colors.GRAY
}}>Discover your next adventure effortlessly.Personalized itineraries at your fingerprints.Travel smarter with AI-driven insights</Text>
<View style={styles.button}>
<Text style={{
color:Colors.WHITE,
textAlign:'center',
fontFamily:'outfit',
fontSize:17

}
}>Sign In With Google</Text>


</View>


</View>

</View>
  )
}
const styles = StyleSheet.create({

container:{
backgroundColor:Colors.WHITE,
marginTop:-20,
borderTopRightRadius:20,
borderTopLeftRadius:20,
height:'100%',
padding:25,

},
button:{

  padding:15,
  backgroundColor:Colors.PRIMARY,
  borderRadius:99,
marginTop:'25%'


}



})