// template generated by typing rnf using installed extension
import { View, Text,Image, StyleSheet, TouchableOpacity } from 'react-native'
import React from 'react'
import { Colors } from '@/constants/Colors'
import { useRouter } from 'expo-router'

export default function Login() {
  const router=useRouter();
  return (
    <View>
    <View>
      <Image source={require("./../assets/images/login.png")}
      style={{width:'100%',
        height:400
      }}
      />
    </View>
    <View style={styles.container}>
<Text style={{fontSize:28,fontFamily:'outfit-bold',textAlign:'center',marginTop:20}}>
Ai Travel Planner
</Text>
<Text style={{
  fontFamily:'outfit',
  fontSize:17,
  textAlign:'center',
  color:Colors.GRAY
}}>Discover your next adventure effortlessly.Personalized itineraries at your fingerprints.Travel smarter with AI-driven insights</Text>
{/* //we will use touchable opacity which is provided by react native ,so that on click of button login signup page is rendered */}
{/* <View style={styles.button}>
<Text style={{
color:Colors.WHITE,
textAlign:'center',
fontFamily:'outfit',
fontSize:17

}
}>Get Started</Text>


</View> */}

<TouchableOpacity style={styles.button}
onPress={()=>router.push('auth/sign-in')}

>
<Text style={{
color:Colors.WHITE,
textAlign:'center',
fontFamily:'outfit',
fontSize:17

}
}>Get Started</Text>


</TouchableOpacity>
</View>

</View>
  )
}
const styles = StyleSheet.create({

container:{
backgroundColor:Colors.WHITE,
marginTop:-20,
borderTopRightRadius:20,
borderTopLeftRadius:20,
height:'100%',
padding:25,

},
button:{

  padding:15,
  backgroundColor:Colors.PRIMARY,
  borderRadius:99,
marginTop:'25%'


}



})