// template generated by typing rnf using installed extension
import { View, Text } from 'react-native'
import React from 'react'

export default function Login() {
  return (
    <View>
      <Text>Login</Text>
    </View>
  )
}